---

- name: prepare local
  hosts: localhost
  roles:
    - local_prepare

- name: setup python2
  hosts: masters:workers
  become: true
  gather_facts: no
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts

- name: gather_facts on masters and workers
  hosts: masters:workers

- name: Setup etcd, flannel, docker
  hosts: masters:workers
  become: true
  roles:
    - basic

- name: configure masters
  hosts: masters
  become: true
  roles:
    - k8s_master

- name: configure workers
  hosts: workers
  become: true
  roles:
    - k8s_worker

- name: configure client
  hosts: localhost
  roles:
    - k8s_client

- name: configure dns
  hosts: localhost
  roles:
    - k8s_dns
