---

- name: prepare local
  hosts: localhost
  roles:
    - local_prepare

- name: setup python2
  hosts: masters:slaves
  become: true
  gather_facts: no
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts

- name: gather_facts on masters and slaves
  hosts: masters:slaves

- name: Setup etcd, flannel, docker
  hosts: masters:slaves
  become: true
  roles:
    - basic

- name: configure master
  hosts: masters
  become: true
  roles:
    - k8s_master

- name: configure slave
  hosts: slaves
  become: true
  roles:
    - k8s_slave

- name: configure client
  hosts: localhost
  roles:
    - k8s_client

- name: configure dns
  hosts: localhost
  roles:
    - k8s_dns
