# The basic role install all necessaary pacakges for all host (ubuntu16.04)
# ex:
#   - etcd
#     * This is service/peer discovery and distributed key-value system.
#     * service would be setup to served directly.
#   - flannel
#     * This is tool to create virtual network for docker across host
#     * service WON'T be run after this roles played
#   - docker
#     * Docker daemon
#     * Run default config without flannel
#   - kubernetes source and executable
#     * Download kubernetes source and setup executable files
---

- include: _etcd.yaml
- include: _flanneld.yaml
- include: _docker.yaml
- include: _k8s.yaml
