---

- name: clear previous k8s certificates
  file: path={{K8S_DIR}}{{K8S_VERSION}}/ssl state=absent

- name: promise k8s certificates
  file: path={{K8S_DIR}}{{K8S_VERSION}}/ssl state=directory recurse=yes owner=root group=root

- name: Copy certificates generate script
  template:
    src: gen_ca.sh.j2
    dest: "{{K8S_DIR}}{{K8S_VERSION}}/ssl/gen_ca.sh"
    owner: root
    group: root
    mode: 0700
  
- name: Generate certificates
  shell: "cd {{K8S_DIR}}{{K8S_VERSION}}/ssl && ./gen_ca.sh"

- name: Config kube-api-server service
  template:
    src: kube-api-server.service.j2
    dest: /lib/systemd/system/kube-api-server.service
    owner: root
    group: root
    mode: 0644

- name: Start/Restart kube-api-server service
  systemd: name=kube-api-server state=restarted daemon_reload=yes enabled=yes

- name: Config kube-controller-manager service
  template:
    src: kube-controller-manager.service.j2
    dest: /lib/systemd/system/kube-controller-manager.service
    owner: root
    group: root
    mode: 0644

- name: Start/Restart kube-controller-manager service
  systemd: name=kube-controller-manager state=restarted daemon_reload=yes enabled=yes

- name: Config kube-scheduler service
  template:
    src: kube-scheduler.service.j2
    dest: /lib/systemd/system/kube-scheduler.service
    owner: root
    group: root
    mode: 0644

- name: Start/Restart kube-scheduler service
  systemd: name=kube-scheduler state=restarted daemon_reload=yes enabled=yes
